### ISSUE TITLE
KASHacters Multi Character

### ISSUE THREAD

**Issue by jonassvensson4** [jonassvensson4/jsfour-atm#12]
Some people seem to get an error in the server,lua on row 132 when using the KASHacters Multi Character resouce.

I've never used that resource and I don't know what it changes. I'm making this issue for others to find. And to clearify that there's not support for other resources. If you install a resource that breaks this resource it's up to you to find the solution for it - since it's you who are using it, not me. There are 800 000+ different resources in use, I can't test them all.

If you're using the KASHacters resource and have found a solution for this, feel free to share it with everyone else as a forked repo or make a pull request :)

**Comment by fimbriano** [comment]
This happens I think because it's checking for the character ID before you have finished actually loading in, so it hasn't really grabbed your ID yet. If the player relogs it will create their bank account still. I haven't found how to fix this, I'm wondering if increasing the citizenWait time will help at all.
