### ISSUE TITLE
Regarding the MDC

### ISSUE THREAD

**Issue by iPraque** [jonassvensson4/jsfour-atm#20]
Hello,

first of, sorry for interrupting you through here. I tried any other way to contact you regarding an issue with the MDC but I was unable to. Sorry again.

''If you want to make someone wanted but you don't know their DOB you can use enter Unknown as DOB.''

This does not seem to work for me. I do not get any errors in the F8 console. The person does not get added to the wanted list It works if I put the DOB+Lastdigits combo. Is there any way you could support me?

Kind regards.

**Comment by jonassvensson4** [comment]
Hello! 

Yes you were unable to create a new issue in the jsfour-mdc repository because it has been archived. 

I've been prodiving support and helping people with that resource the past year. Most of the issues have been server related. I understand your frustration if it's not working as intendend. But I'm sorry, it has been archvied due to the fact that I won't provide any more support. And some other reasons such as it's dependent on my jsfour-register (or rather the lastdigits) which also has been archived.

Your best luck would be to browse through closed issues and you might find a smiliar issue. Otherwise you'll have to debug it yourself.

I'm sorry.
