### ISSUE TITLE
Money not being withdrawn

### ISSUE THREAD

**Issue by Janicki92** [jonassvensson4/jsfour-atm#21]
Players are seeing it removed from bank, but does not add to cash.  Happens sporadically, no errors in console.  Needs a fix.

**Comment by Janicki92** [comment]
Update:  Once in a while you'll see JSFOUR-ATM: ERROR in the server log.  Nothing else.

**Comment by jonassvensson4** [comment]
There are 2 lines of codes that withdraws the money and as you've already said the player can see the money being removed from the bank. I assume it's the notification that you're talking about. Which means those 2 lines of code stops working. And there's nothing I can do about it since they're ESX functions.

**JSFOUR-ATM: ERROR** gets printed out if the player is trying to bug the system. When you open the ATM it stores the money as a local variable. When a player tries to withdraw or deposit money it double checks if the player has that amount of money. You could simply add a notification that's telling the player that they don't have that amount of money instead of that print.

The error can't have anything to do with your issue since you're telling me that the players can see the money being removed.
