### ISSUE TITLE
SCRIPT ERROR: @jsfour-atm/server.lua:128: attempt to index a nil value

### ISSUE THREAD

**Issue by Fowman** [jonassvensson4/jsfour-atm#22]
What could this Cause ? 
i didnt change anything except of the language.

**Comment by jonassvensson4** [comment]
Seems like you're using a modified version the server.lua? I can't find anything on row 128 that's trying to index a value.

**Comment by jonassvensson4** [comment]
It might be this line of code you're refeering to since that's the one that's closest to row 128.
https://github.com/jonassvensson4/jsfour-atm/blob/master/server.lua#L132

Seems like it's a similar issue that my jsfour-idcard had, might give that a try:
https://github.com/jonassvensson4/jsfour-idcard/issues/10#issuecomment-524938198
