### ISSUE TITLE
Pin info

### ISSUE THREAD

**Issue by TheDjRider** [jonassvensson4/jsfour-atm#23]
Hello, 

is there any way players to set themself PIN to their cards. 
I think long ago (year or more) I even remember the same ATM, but I had to set my PIN at a bank and then use the ATM.

Thanks :)

**Comment by TheDjRider** [comment]
Also, have problem with money transfer. It show that money were taken from my balance and after close the page they were returned to me.

**Comment by jonassvensson4** [comment]
> is there any way players to set themself PIN to their cards.

I never added that because I personally think it would be hard to remember a code along side with all the other information you need to remember.

It's fairly easy to let the players choose their own pin code. The easiest way would probably be to add an extra input field in the "bank window". Save the pin to the database and then fetch it when a player is trying to access the ATM.

I think someone has made an old fork of this repo that lets you do this, but I have no idea which one. 
> Also, have problem with money transfer. It show that money were taken from my balance and after close the page they were returned to me.

Are you using ESX? How does it return the money? Do you get an notification that's telling you that you've gotten the money? Or does it just add the money back to your account inside the ATM?

**Comment by TheDjRider** [comment]
For the PIN i will search and thans for info. I think can't do it alone to add field&db option. 
Other side i think is better they to set their own pin.

For money i'm on ESX yes, and when open the bank and write other person number, remove the money from down left and when i close my bank screen money are still in my account.

**Comment by jonassvensson4** [comment]
I added the option to change the pincode by visiting the bank. I have tested it the best I could, might be some bugs that I haven't found yet. Please let me know if you do find one.

I found a typo in the server.js that might've been the reason why the transfer event wasn't working correctly. Try to re-download the resource and let me know if that fixed it.

**Comment by TheDjRider** [comment]
Hello, 
i update the version but now the bank menu didn't open. Only load mouse cursor and nothing other.

Also i drop the old atm table in DB and upload the new one but server console show this - 

> [ERROR] [MySQL] [mysql-async] An error happens on MySQL for query "INSERT INTO `jsfour_atm` (`identifier`, `account`) VALUES ('steam:1100001073506b7', 150795933)": ER_NO_DEFAULT_FOR_FIELD: Field 'pincode' doesn't have a default value

**Comment by jonassvensson4** [comment]
I forgot to add the default value to the pincode column in the SQL file. That's probably why the bank menu didn't open. I've updated the SQL file.

**Comment by TheDjRider** [comment]
Now everythink is OK now. 
Thanks

**Comment by TheDjRider** [comment]
Now everything is OK now.
Thanks
