### ISSUE TITLE
Cannot deposit or withdraw money

### ISSUE THREAD

**Issue by Rado236** [jonassvensson4/jsfour-atm#24]
Hi! I just installed the new version of the script and also put the SQL file into my database. When I go to the atm I click on the amount of the money i want to withdraw but nothing happens. Also the bank UI is not opening. I am using the latest version of ESX.

**Comment by jonassvensson4** [comment]
I haven't tried this new version of this resource with ESX since I'm not using ESX anymore. I might have missed something in the server. Feel free to debug it and make a pull request if you find something that should be changed.

The Bank UI should open. Unless you're getting some kind of error in the console.

**Comment by Rado236** [comment]
I dont get any error.

**Comment by TheDjRider** [comment]
I can also deposit and withdraw but when i try to deposit from ATM maybe 100$ but i have 1000$ it auto deposit all my money from my character :(
Also from Bank can't deposit only can withdraw.
Transfer are not working, when i type other player _Account Number_ nothing happend.

**Comment by jonassvensson4** [comment]
Everything you've mentioned uses ESX functions. When I translated the resource into javascript I didn't use ESX myself so I couldn't test all the functions. I just assumed they were working like they used to. 

I'm sorry, I would like to help you debug the ESX part but I can't since I'm not using it anymore. As I previously said, you're more than welcome to debug it yourself and make a pull request.

**Comment by Rado236** [comment]
I will just use the older version and try to implement the blips into it.

**Comment by jnsvns** [comment]
Bank deposit has been fixed. I can't seem to re-create the other issues. Feel free to debug the ESX part and make a pull request, I'm truly sorry that I can't be of more help.
